name: "Validate Gradle Wrapper"
on:
  push:
    branches:
      - main
    paths:
      - 'gradle/**'
  pull_request:
    branches:
      - main
    paths:
      - 'gradle/**'
jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
